### ISSUE TITLE
Project Hub `Open Project` should be called `Import Project`

### ISSUE THREAD

**Issue by adriengivry** [adriengivry/Overload#115]
`Open Project` is a bad name for this feature as its purpose is to import a project that has been moved onto the disk or downloaded.

We should rename this button into `Import Project`

**Comment by Kubiisek** [comment]
Do you think if it's called `Import Project` it should still open the project or just register it?

**Comment by adriengivry** [comment]
Actually I thought about this and I still can't decide... We can:
- Have 2 buttons (Import and Import+Open) to provide a quick equivalent of the current Open button
- Loose the ability to import (aka register) and open at the same time
- Find another term that can efficiently announce that the project will get registered and opened

**Comment by Kubiisek** [comment]
I think it's fine as it is. If you take a look for example on VS, it does the same thing as we are doing currently:
![image](https://user-images.githubusercontent.com/38976370/88629385-79d3cf80-d0af-11ea-97ca-515c7e61da93.png)
It opens the project and adds it to their list.

**Comment by adriengivry** [comment]
Ok great! We can close this issue for now, if anyone come up with a better solution we will reopen this issue
