### ISSUE TITLE
API:IDrawable virtual destructor non-implemented, potential undefined behaviour

### ISSUE THREAD

**Issue by litelawliet** [adriengivry/Overload#151]
**Description**
The class `IDrawable` in `OvUI::API` doesn't contains a virtual destructor. It sounds harmless and it might be since compilers probably fills that by itself, however the lack of a virtual destructor in this situation may result in an undefined behavior when deleting a derived-class.

**Expected resolution**
For good mesure and best practice it is better to define that virtual destructor by ourself in IDrawable by adding :
```c++
protected:
    virtual ~IDrawable() = default;
```
That should guarantee a proper dynamic dispatch mechanism when destroying at runtime (derived-class to base-class)

**Comment by sgavil** [comment]
Hello, can I contribute to this issue?

**Comment by litelawliet** [comment]
Hello, unfortunately this issue has been resolved and merged : https://github.com/adriengivry/Overload/pull/152

**Comment by adriengivry** [comment]
@litelawliet Just letting you know that you should consider adding "Fixes #xxx" onto your PR descriptions to automatically close them when merged.

**Comment by maxbrundev** [comment]
> Hello, can I contribute to this issue?


If you want there is other issues with the Good First Issue Label! 😄
