### ISSUE TITLE
Open the project and close it right away.

### ISSUE THREAD

**Issue by Gaimo** [adriengivry/Overload#195]
**Description**
When I try to open some project, overload closes right away.

**To Reproduce**
1. open Overload
2. create a project
3. click open project

**Screenshots**
![image](https://i.ibb.co/0YDPP1h/unknown.png)

**Comment by adriengivry** [comment]
May I ask you the Overload version used?

**Comment by Gaimo** [comment]
1.3.0

**Comment by maxbrundev** [comment]
I faced the same issue recently, it was due to the old files from the AppData OverloadTech folder that where created with an older version of the Engine, when I deleted them I have been able to open my project.
Path: AppData\Roaming\OverloadTech\

Make sure to delete the content of this folder

**Comment by ChenXiang0810** [comment]
I faced the issue too. If you can not run the Overload well still after trying the method maxbrundev provided, I think you could try to run it in VS with F5(Start Debugging). Though I don't know why, it does work in my computer.

**Comment by adriengivry** [comment]
@Gaimo Any update on this issue? Are you still encountering it?

**Comment by Gaimo** [comment]
I bought a video card, now it's working.

**Comment by ShigotoShoujin** [comment]
Greetings, I created a pull request and updated the issue.

Pullrequest: https://github.com/adriengivry/Overload/pull/198#issue-779979293
Issue: https://github.com/adriengivry/Overload/issues/197#issue-1052792862


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
