### ISSUE TITLE
When a new project is created, the program directly reports an error

### ISSUE THREAD

**Issue by wangdemon** [adriengivry/Overload#197]
When I create a new project in Overload, it reports an error.
![error](https://user-images.githubusercontent.com/20681339/140773402-7002caa8-672a-4cf8-81bf-29b5b5c087d4.png)
My laptop hardware is poor. CPU is i5-3230M, Graphics card is NVIDIA 630. But the Graphics card 630 supports OpenGL 4.5.
![info](https://user-images.githubusercontent.com/20681339/140774259-19129a39-1d81-4956-bd6f-65a5971217c9.png)

**Comment by adriengivry** [comment]
Interesting one. Is your discrete graphics card set as the default graphics processor to use in your Nvidia Configuration Panel?

**Comment by wangdemon** [comment]
Yes, I have set the NVIDIA graphics card as the default graphics display card.I also set the default NVIDIA graphics card when the Overload program starts.
![无标题](https://user-images.githubusercontent.com/20681339/141437149-2ff0d03c-b3b7-4cc5-9a79-38560f2bb05f.png)

**Comment by wangdemon** [comment]
I found that the problems described above do not occur when I use a desktop computer. The graphics card of my desktop computer is amd 560. So I think Overload needs a better performance graphics card to run.

**Comment by adriengivry** [comment]
From what I can see online, this GPU (GeForce GT 635M) only supports OpenGL 4.2, while Overload requires OpenGL 4.3 or higher. I think we should add a popup window warning the user when specifications aren't met.

**Comment by ShigotoShoujin** [comment]
Greetings, a fix is proposed in the follow pull request https://github.com/adriengivry/Overload/pull/198#issue-779979293
Please review and suggest any improvements.

**Comment by wangdemon** [comment]
OK, I understand. Thank you.
