### ISSUE TITLE
Where can I download the beautiful example shown in the screenshot？

### ISSUE THREAD

**Issue by wangdemon** [adriengivry/Overload#202]
The beautiful example shown in the screenshot, where can I download it？ I want to experience it.
![1](https://user-images.githubusercontent.com/20681339/142223460-e8e6c9a3-ebab-4787-bfa7-6dee5689bc29.png)
![2](https://user-images.githubusercontent.com/20681339/142223478-b2c40d85-f17f-4ad4-b0d4-312bfe2428c8.png)
![3](https://user-images.githubusercontent.com/20681339/142223489-d3dbc0e6-44b4-4aed-a0b7-872e4d8bf032.png)

**Comment by adriengivry** [comment]
1. This one isn't available (hasn't been shared)
2. This is Cargo, the demo game we made with Overload. You can find it on our Discord server (see the `resources` channel)
3. This is from the Showroom project we made, which is also in the `resources` channel on Discord

**Comment by wangdemon** [comment]
I want to experience a full examples of Overload. Where should I download it?

**Comment by adriengivry** [comment]
Check out our samples on Discord (`resources` channel)

**Comment by adriengivry** [comment]
@wangdemon By the way, we recently opened "GitHub Discussions" for Overload, so if you have any other question that is not an issue, you can post there: https://github.com/adriengivry/Overload/discussions
