### ISSUE TITLE
Create an empty project, click the run button, and the Overload will crash directly

### ISSUE THREAD

**Issue by wangdemon** [adriengivry/Overload#206]
I create a  new program, click the run button, and the Overload will crash directly.
My graphics card is NVIDIA 1060, which supports OpenGL 4.3.I also set the default to use a high-performance graphics card
![1](https://user-images.githubusercontent.com/20681339/142836260-de360ab4-6988-4852-a3fd-ed029fd404e1.png)

![2](https://user-images.githubusercontent.com/20681339/142836276-062ceb17-aa90-4323-ace9-5a5eeb1df083.png)
![动画](https://user-images.githubusercontent.com/20681339/142836412-422eba42-fd9d-4891-b2fe-c197bb9bf262.gif)

**Comment by wangdemon** [comment]
When I run the program after compiling the code, there will be a crash.
![动画1](https://user-images.githubusercontent.com/20681339/142891592-136e244c-cacc-46f1-aca9-aad135c00303.gif)

**Comment by litelawliet** [comment]
What nvidia driver version are you on ?

**Comment by wangdemon** [comment]
The nvidia driver version is 389.04
![微信截图_20211122235214](https://user-images.githubusercontent.com/20681339/142892898-498ffcf3-264b-4bf1-8b44-b04f28f593d3.png)
.

**Comment by adriengivry** [comment]
This driver is from 3 years ago, I would suggest updating it. Let us know if it fixes the issue

**Comment by adriengivry** [comment]
No update from author, closing for now
