### ISSUE TITLE
Update key engine dependencies

### ISSUE THREAD

**Issue by sierra-zero** [adriengivry/Overload#209]
**Problem this feature should fix**

A number of engine dependencies are using outdated versions.
Some dependencies have received stable updates that the project is not yet benefiting from.
A number of open Issues require or would benefit from these updates, such as [Gamepad Support](https://github.com/adriengivry/Overload/issues/16) and [No Diagonal Window Cursor](https://github.com/adriengivry/Overload/issues/121).
Also they will bring associated bug fixes (although of course, potential new issues).

Updates are proposed for the following dependencies:

- ~GLEW:  2.1 -> 2.2 (Jan 2021, primarily bugfixes).~
- [ ] GLFW: 3.2 -> 3.3.5 (October 2021, improvements and bugfixes).
- ~IMGUI (docking): 1.77 WIP -> 1.85 or 1.86 WIP (Oct 2021, improvements and bugfixes).~
-  ~EDIT: ASSIMP: 5.0.1 -> 5.1.1 (Nov 2021, bugfixes).~

**Expected solution**

- ~Initially, an update to GLEW to proceed first. as the version jump consists mostly of minor bugfixes and should have minimal impact.~ 
- GLFW and IMGUI to be updated concurrently due to codependency of imguiGLFW, to minimize breaking code.
- ~EDIT: ASSIMP a small increase in versions, low chance of breaking changes.~

**Comment by adriengivry** [comment]
I'm a bit resistant to updating in general. If it works, don't change it. If we can benefit from a critical bug fix, a feature or a necessary performance boost, then updating a third-party can be considered. We should be careful with updates to avoid introducing instabilities here and there.

I would also like to move to a git sub-module approach in the future.

For now, we should evaluate the impact of all these updates, and see which ones are necessary (especially for the issues you mentioned).

**Comment by sierra-zero** [comment]
I can appreciate your hesitancy.
Git sub-modules are great 👍 

GLFW would be required ... and updating it compiles and runs without apparent issues.

For reference:
I had thought IMGUI would be a necessary bump, but may get away with it. Requires a small number of changes.
GLEW had no obvious issues compiling or in test scenes afaik either. 
Didn't try ASSIMP ...  but would be fairly easy to test its compatibility as its just static meshes and no animation yet.

**Comment by adriengivry** [comment]
What would be the benefit of each of these updates?

**Comment by sierra-zero** [comment]
To be clear, i'm no longer proposing to add them to Overload.

**Comment by adriengivry** [comment]
Oh yeah sorry I misread that! So you still suggest GLFW update for https://github.com/adriengivry/Overload/issues/16 and https://github.com/adriengivry/Overload/issues/121, correct?

**Comment by sierra-zero** [comment]
Well, for diagonal cursor it is necessary. 
And gamepad support has been significantly improved in recent versions, but not strictly necessary.

So i would suggest to try it, revert if required.

**Comment by adriengivry** [comment]
Looks good to me, diagonal cursor is a sufficient requirement to make the move IMO! And gamepad improvement is a valuable nice to have for us
