### ISSUE TITLE
Could not find Start Scene after Build Game

### ISSUE THREAD

**Issue by avi9111** [adriengivry/Overload#217]
**Description**
After I gen game.exe, it says "............ could not find the scene"

**To Reproduce**
1.I created a screen, 
2.Set it in Project Setting Window.
3.Build Game
4.Run it

**Expected behavior**
I could read the code, but it was confuse as a new user , how could a new user figure out what's wrong with the output of "buid game" and how to fix it??

**Screenshots**
![image](https://user-images.githubusercontent.com/10510839/163207067-cea6df86-fbaa-4303-9a5b-bb68a868b752.png)
![image](https://user-images.githubusercontent.com/10510839/163207216-e4c8b497-9a3c-4168-9eb7-823c1fa40756.png)

![image](https://user-images.githubusercontent.com/10510839/163207380-2e7146cf-65fa-4a02-a842-cead82fe17aa.png)

**Comment by adriengivry** [comment]
I can't seem to reproduce the issue, can you attach an archive of your project?

**Comment by isncg** [comment]
@avi9111 Did you click the Apply button in project setting? I got same msgbox and later I noticed that green button there has to be clicked.

**Comment by adriengivry** [comment]
No update from author, closing for now
