### ISSUE TITLE
considered using Qt as the UI

### ISSUE THREAD

**Issue by wangdemon** [adriengivry/Overload#238]
Qt is used by many people and it is very easy to use.

Qt can make a very beautiful UI.

If you replace imGui with Qt, it would be better.

**Comment by litelawliet** [comment]
I'd argue ImGUI is also used by many people (big companies as well) and is very easy to use.
The philosophy between Qt and ImGUI is also different and would need to rework all the UI internals.

You're saying Qt would be better, while it is most certainly true for certain things... why would we want Qt for Overload ?

What can Qt bring on the table other than being "better" according to you ?

You're free to work on that but we can hardly justify a merge or our time while there are other priorities on the roadmap. Without real limitations from ImGUI (for the current use and future of the editor) and very interesting features from Qt that we would absolutly need, that will stay a very low priority task.
