### ISSUE TITLE
Mouse Button wrong documentation 

### ISSUE THREAD

**Issue by SolarcGit** [adriengivry/Overload#247]
![image](https://github.com/adriengivry/Overload/assets/72672879/310cfe26-7105-4c7b-84f5-1ffd98f2d362)

The wiki says they are called MOUSE_BUTTON_... but in the code its only BUTTON_...

![image](https://github.com/adriengivry/Overload/assets/72672879/9a85b654-f146-4235-8b4f-8ca6456a13ac)

**Comment by adriengivry** [comment]
Fixed in https://github.com/adriengivry/Overload/wiki/MouseButton/b1d2fe3e87490db237507d4148d6c6950d0c3805
