### ISSUE TITLE
 Some suggestions

### ISSUE THREAD

**Issue by dosusang** [adriengivry/Overload#304]
I believe that the rendering layer may benefit from some restructuring. It's quite inconvenient to add new rendering features at the moment. Additionally, the namespace of the engine seems overly complex.
![EAU@NI4R1{970{F@6}%6J0I](https://github.com/adriengivry/Overload/assets/52528872/bdc45de9-15f4-4c92-aa89-d30d96dd966f)

**Comment by adriengivry** [comment]
Not sure there is much we can do here. "engine seems overly complex" isn't something we can address just like that. We also just reworked the rendering engine to allow for new render features to be added easily.
