### ISSUE TITLE
Add hint to prioritize AMD discrete GPU

### ISSUE THREAD

**Issue by adriengivry** [adriengivry/Overload#305]
**Problem this feature should fix**
Overload isn't setting the appropriate hint for the application to prioritizing using an AMD discrete GPU if available.

**Expected solution**
Update our [FORCE_DEDICATED_GPU](https://github.com/adriengivry/Overload/blob/5676ac9fec33e3e51945dd1beac62a3f404d7b2d/Sources/Overload/OvRendering/include/OvRendering/Utils/Defines.h#L11) macro to add:
```cpp
// Hint that the discrete gpu should be enabled on optimus/enduro systems
// NVIDIA docs: http://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf
// AMD forum post: http://devgurus.amd.com/thread/169965
extern "C"
{
    __declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;
    __declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1; // <-- Add this line
}
```

**Comment by eXpl0it3r** [comment]
Relates to #40

Can also just be: `DWORD NvOptimusEnablement = 1`

SFML uses `unsigned int` not sure it matters.

https://github.com/SFML/SFML/blob/b50f62da43e0d7dc2b2855730e78a4ccf5048249/include/SFML/GpuPreference.hpp#L62-L70

**Comment by adriengivry** [comment]
Fixed by https://github.com/adriengivry/Overload/pull/316
