### ISSUE TITLE
[Bug] Uninitialized variable

### ISSUE THREAD

**Issue by carlcc** [adriengivry/Overload#72]
Hi,

The diff can be show [here](https://github.com/carlcc/Overload/commit/cf2486f1c47eede7ac37978ce2548179041cadb6)

Strangely, this bug causes crash only when using my cmake scripts...

The original `sln` project does not...

P.S.
Uhm... I wrote a simple cmake script, and is about to make a PR...
But I just found... I've done the same thing... there is already a PR doing the same thing. ;-(
My version of cmake scripts are simpler (more straight forward)... So I decided to give my PR.

So  I just tell you the bug I found..

Regards.

BTW. I think you guys would better use a `.clang-format` file to format the code

**Comment by adriengivry** [comment]
Thanks for your contribution ! I’ll review it soon
