### ISSUE TITLE
Scene cannot load in the Game.exe file generated after building the game

### ISSUE THREAD

**Issue by Kzapas** [adriengivry/Overload#89]
After compiling the game using the build game command, it throws an error suggesting that my scene could not be loaded. This is, however, using v.1.3.0 of Overload.

![5](https://user-images.githubusercontent.com/33299760/84081829-b424c880-a9ac-11ea-949b-8bf152c755b4.PNG)

**Comment by wangdemon** [comment]
I also encountered this situation. How did you solve it？

**Comment by adriengivry** [comment]
@wangdemon Can you provide a log of the output you got?

**Comment by wangdemon** [comment]
> @wangdemon Can you provide a log of the output you got?

The problem has been solved.There's a bug here. If the file name of the Assets is not changed and the default name "New Scene.ovscene" is adopted. 
![1](https://user-images.githubusercontent.com/20681339/140527157-57532401-08f0-4335-a4ac-a148edca0a58.png)
It will prompt an "Scene loading failed"error.
![2](https://user-images.githubusercontent.com/20681339/140527219-7601ceb8-6773-49b3-be61-06d07fc6922b.PNG)

**Comment by adriengivry** [comment]
When building the game you have to set the startup scene, otherwise it won't work. We should prompt a warning message before building if the startup scene hasn't been found OR has been renamed

**Comment by wangdemon** [comment]
That's OK. Thank you very much!
