### ISSUE TITLE
Translating/Rotation/Scaling in world space

### ISSUE THREAD

**Issue by adriengivry** [adriengivry/Overload#91]
**Problem this feature should fix**
Some parts of Overload (Ex: gizmos, scripting), require the ability to translate/rotate/scale an object in world space.

**Expected solution**
We should add `SetWorldPosition`, `SetWorldRotation`, `SetWorldScale` to our transforms (`FTransform` and `CTransform`). Lua binding should get updated after adding these new methods

**Comment by sierra-zero** [comment]
Believe this issue can be closed.
Happy to address anything outstanding.
