### ISSUE TITLE
Adding `OvMaths::FMatrix4::Rotation()` and `OvMaths::FMatrix4::Rotate()`

### ISSUE THREAD

**Issue by adriengivry** [adriengivry/Overload#92]
**Problem this feature should fix**
There are some inconsistencies between our matrix construction for translation, scale and rotation:
- [X] Create a translation matrix using `OvMaths::FMatrix4::Translation(translationVector)`
- [X] Create a scaling matrix using `OvMaths::FMatrix4::Scaling(scalingVector)`
- [x] Create a rotation matrix using `OvMaths::FMatrix4::Rotation(rotationQuaternion)`

Morehover, when we already have a transformation matrix, matrix manipulation is inconsistent:
- [X] Translate matrix using  `OvMaths::FMatrix4::Translate(matrix, translationVector)`
- [X] Scale matrix using  `OvMaths::FMatrix4::Scale(matrix, scalingVector)`
- [x] Rotate matrix using  `OvMaths::FMatrix4::Rotate(matrix, rotationQuaternion)`

**Expected solution**
We should implement:
- `OvMaths::FMatrix4::Rotation(rotationQuaternion)`
- `OvMaths::FMatrix4::Rotate(matrix, rotationQuaternion)`

These new methods should also get exposed to lua scripting

**Comment by litelawliet** [comment]
I think this issue can be closed since it is merged and fully completed by kmqwerrty ?

**Comment by adriengivry** [comment]
Nope, lua binding is still to be done
